<?php

	$nprAPIKey = 'ADD_YOUR_NPR_API_KEY_HERE';

	$nytAPIKey = 'ADD_YOUR_NYTIMES_API_KEY_HERE';

	$googleMapsAPIKey = 'ADD_YOUR_GOOGLE_MAPS_API_KEY_HERE';

	$placeMakerAPIKey = 'ADD_YOUR_PLACEMAKER_API_KEY_HERE';

?>